### ISSUE TITLE
Typed defines are not supported.

### ISSUE THREAD

**Issue by xlab** [cznic/cc#3]
```c
typedef unsigned long PaStreamCallbackFlags;

#define paInputUnderflow   ((PaStreamCallbackFlags) 0x00000001)
```

The `paInputUnderflow ` macro gets nil `Value` in macro map (`map[int]*cc.Macro`).

Digging into:

```go
	macro.Value, macro.Type = p.lx.parsePPConstExpr0(rl, p)
```

...leads to the sloppy slope in the code :)

```go
for i, tok := range l.toks {
		if tok.Rune == IDENTIFIER {
			if p.macros.m[tok.Val] != nil {
				l.report.ErrTok(tok, "expected constant expression")
				return nil, nil
			}

			tok.Rune = INTCONST
			tok.Val = id0
			l.toks[i] = tok
		}
	}
```

Which can't handle typecasts and parens well, so `yyParse` gets confused on extra parens:

```go
	l.state = lsConstExpr0
	if err := yyParse(l); err == 0 {
		e := l.constantExpression
		return e.Value, e.Type
	} else {
		// butt hurt!
		log.Println("bad parse:", l.toks)
	}
```

**Comment by cznic** [comment]
ouch 😟

**Comment by cznic** [comment]
But thanks for unearthing the bug!

**Comment by xlab** [comment]
```
failed to parse! [portaudio/portaudio.h:442:54: ")"]
```

the code:

```
#define paCustomFormat   ((PaSampleFormat) 0x00010000)
//                                                                                              ^ this
```

**Comment by xlab** [comment]
This is where I'm perfectly fine with using the expression as-is :)

**Comment by cznic** [comment]
The problem is that the preprocessor has no idea what an expression is beyond the argument of #if or #elseif; and after preprocessing, any #define constant names are lost. The only thing preserved is another enum constant name(s).

I have no idea how to support cgogen, or any other tool for that matter, with "pretty" enum constant expression tokens. Do you?

**Comment by xlab** [comment]
Well I can handle "pretty" enum constants using some domain-specific hacks, I'd never agree this should be generalized in any way. But the bug there is that:

```c
#define paInputUnderflow   ((PaStreamCallbackFlags) 0x00000001)
```
...is a valid C code, but the value of `paInputUnderflow` reported as `<nil>`. So although I can use the expression as-is, the value still remains unknown :(

**Comment by cznic** [comment]
The `Value` of a `Macro` in the `Macros` map is non nil only for constant expressions. Even if

```c
#define paInputUnderflow   ((PaStreamCallbackFlags) 0x00000001)
```

looks quite constant, it is *not* a constant expression wrt the C specification. The problem is not in the specification, it's once again a problem of the preprocessor having no idea how to evaluate the above because it has no concept of C types above the predeclared types. So it can evaluate for example

```c
#define foo (unsigned)42
```

or even

```c
#define bar (char*)1
```
but `paInputUnderflow` will yield a non-nil value only after evaluated as a part of post preprocessing expression when the type `PaStreamCallbackFlags` is known. Even worse, it depends on scope where `paInputUnderflow` is used. But after preprocessing, any mention of `paInputUnderflow` is lost so once again: the expansion of `paInputUnderflow` is not a constant expression and AFAICT there is no way it can ever have a non nil `Value` in the `Macros` map value.

**Comment by cznic** [comment]
```go
for i, tok := range l.toks {
        if tok.Rune == IDENTIFIER {
            if p.macros.m[tok.Val] != nil {
                l.report.ErrTok(tok, "expected constant expression")
                return nil, nil
            }

            tok.Rune = INTCONST
            tok.Val = id0
            l.toks[i] = tok
        }
    }
}
```

This snippet SGTM. After expansion a constant expression cannot have any identifiers left. If there are any left, the specification mandates to evaluate them as zero if not a macro name. A macro name should be expanded unless not on a non-expand list. A macro name on a non-expand list cannot be evaluated to any value.

It now seems to me that even, as mentioned before,

```c
#define foo (unsigned)42
```

is not an constant expression, so I was wrong. Once again, the preprocessor does not understand any type system at all. It can cope only with literal values and operators.

**Comment by xlab** [comment]
Sorry me for my ignorance here, too much Go code has been written and I somehow forgot that the macro are just about identifiers and replacements. I just checked the Reference section of "C Programming Language", it is defined pretty clear, you're right about it. I will close this issue because it's my duty to cope with these expressions from now.
