### ISSUE TITLE
parser: Support omitting function return type.

### ISSUE THREAD

**Issue by cznic** [cznic/cc#78]
```c
f() {}
```
is not valid in C99, but it's sometimes seen in the wild. It's the equivalent of

```c
int f() {}
```

**Comment by andlabs** [comment]
I'd probably have called this `EnableImplicitInt()` personally, since "implicit int" is both the colloquial and quasi-technical name for this feature ([the C++ committee used it as early as 1995](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/1995/N0633.ps); [the C committee used it as early as 1997](http://www.open-std.org/jtc1/sc22/wg14/www/docs/text/n661.txt)) and most compilers refer to it as such...

**Comment by cznic** [comment]
@andlabs SGTM, please feel free to rename the option. It was committed just a few hours ago, the risk of breaking someone's code is low (and I don't mind changing one line in mine's :smile:).
